apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recybot-web
  namespace: ecosystem
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - recybotia.com
        - www.recybotia.com
      secretName: recybot-web-tls
  rules:
    - host: recybotia.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recybot-web
                port:
                  number: 80
    - host: www.recybotia.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recybot-web
                port:
                  number: 80
